ARG IMAGE_VERSION

FROM localhost/podman-container-supervisor:debian-base-${IMAGE_VERSION}

# Update Sources
# Install other Dependencies / recommended Packages
RUN --mount=type=cache,mode=0777,target=/var/cache/apt,sharing=locked \
    --mount=type=cache,mode=0777,target=/var/lib/apt,sharing=locked \
    apt-get update && \
    apt-get install --no-install-recommends -y wget jq net-tools iproute2 bind-tools traceroute tcptraceroute iputils-ping iperf3 tcpdump && \
    echo "Finished installing extra Packages"

# Execute Entrypoint Script
ENTRYPOINT ["/opt/docker-entrypoint.sh"]
